// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbleqpygrzisnxgbhwxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBibGVxcHlncnppc254Z2Jod3hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NzIzODAsImV4cCI6MjA3MjI0ODM4MH0.RfL2nGjIltHAU4HRIPagPV0NaLAMYd3xreOdB-tQ8og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});